language: ruby
rvm:
  - 2.2.3
addons:
  artifacts:
    paths:
      - "tmp/rubycritic"
      - "tmp/sandimeter"
    target_paths: '/'
  s3_region: us-east-1
script:
  - bundle exec rake
  - bundle exec rubycritic app lib
  - bundle exec sandi_meter -g -q --output-path tmp/sandimeter
