language: ruby
rvm:
  - 2.2.3
addons:
  artifacts:
    paths:
      - "tmp/rubycritic"
    target_paths: '/rubycritic'
  s3_region: us-east-1
  debug: true
script:
  - bundle exec rake
  - bundle exec rubycritic app lib
